language: c
sudo: yes
os: linux
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:snaipewastaken/ppa
  - sudo apt-get update -qqq
  - sudo apt-get install -yqq criterion-dev

# We just care that it compiles
script:
  - make clean all
